### ISSUE TITLE
The Video component breaks the layout of the documentation on mobile.

### ISSUE THREAD

**Issue by Bowens20832** [elegantframework/elegant-cli#114]
**Describe the bug**
The new video player component breaks the layout on mobile devices. This is caused by the video player not scaling down in size on mobile.

**To Reproduce**
1. Go to [Elegant Installation](https://www.elegantframework.com/docs/installation)
2. Open Developer tools if not on a mobile device.
3. Scroll down to the video component
4. See how the mobile layout on the page is broken.

**Expected behavior**
The CSS should keep the video player within the mobile layout.

**Screenshots**
![image](https://github.com/elegantframework/elegant-cli/assets/10189130/0359b5d0-b0aa-4a64-b006-8578a2e13200)

**Smartphone (please complete the following information):**

**Additional context**
The fix is probably a simple Tailwind class on a mobile device.

**Comment by Armaan-Singh-Dhillon** [comment]
While troubleshooting the issue, I observed that the Video Component has a fixed width. However, by modifying the width to a percentage value, the issue is resolved. Nonetheless, I would appreciate if you could suggest any alternative solutions that do not require modifying the existing structure to address this bug.
# Before
![before](https://github.com/elegantframework/elegant-cli/assets/108166679/1ee227bb-03b7-4193-8770-3c94b8b1e90d)
# After
![after](https://github.com/elegantframework/elegant-cli/assets/108166679/9286d089-1043-4b26-8c1e-edab33a610d6)
# Code
![code](https://github.com/elegantframework/elegant-cli/assets/108166679/eec7aaf0-7fe8-475e-bf57-1f4d78d94b52)
antframework/elegant-cli/assets/108166679/968982f4-8e07-4ff0-a1df-9f214be18e07)

**Comment by Bowens20832** [comment]
> While troubleshooting the issue, I observed that the Video Component has a fixed width. However, by modifying the width to a percentage value, the issue is resolved. Nonetheless, I would appreciate if you could suggest any alternative solutions that do not require modifying the existing structure to address this bug.
> 
> # Before
> ![before](https://user-images.githubusercontent.com/108166679/251661467-1ee227bb-03b7-4193-8770-3c94b8b1e90d.PNG)
> 
> # After
> ![after](https://user-images.githubusercontent.com/108166679/251661705-9286d089-1043-4b26-8c1e-edab33a610d6.PNG)
> 
> # Code
> ![code](https://user-images.githubusercontent.com/108166679/251661580-eec7aaf0-7fe8-475e-bf57-1f4d78d94b52.PNG) antframework/elegant-cli/assets/108166679/968982f4-8e07-4ff0-a1df-9f214be18e07)

Nice! Thank you for the triage and for taking a look at this @Armaan-Singh-Dhillon. 

It looks like you are on the right track for a fix already. 

Would you like me to assign this issue to you, and let you submit a PR?
